#!/bin/bash
set -euo pipefail
repo=/mnt/e/EBAZ4205-PetaLinux-main/EBAZ4205-PetaLinux-main
target=/home/builder/ebaz4205/petalinux
kernel=/home/builder/src/adi-linux-2020.1
archive=/mnt/e/WSL/PetaLinux-downloads/adi-linux-2020.1.tar.gz
mkdir -p "$target" "$kernel"
if [ ! -f "$kernel/Makefile" ]; then
    tar -xzf "$archive" --strip-components=1 -C "$kernel"
fi
# components/ is generated by PetaLinux configuration, not project source.
rsync -a --ignore-existing --exclude=/components/ "$repo/petalinux/" "$target/"
python3 - "$target/project-spec/configs/config" "$kernel" <<'PY'
import pathlib, sys
path = pathlib.Path(sys.argv[1])
text = path.read_text()
old = 'CONFIG_SUBSYSTEM_COMPONENT_LINUX__KERNEL_NAME_EXT_LOCAL_SRC_PATH="/home/henning/petalinux/ebaz4205/adi-linux-2020-1"'
new = 'CONFIG_SUBSYSTEM_COMPONENT_LINUX__KERNEL_NAME_EXT_LOCAL_SRC_PATH="' + sys.argv[2] + '"'
if old not in text and new not in text:
    raise SystemExit('Unexpected kernel source configuration; refusing to overwrite')
path.write_text(text.replace(old, new))
PY
patchfile="$target/project-spec/meta-user/recipes-kernel/linux/linux-xlnx/0001-Backported-bugfix-for-ADF435x-powerdown.patch"
if patch -d "$kernel" -p1 --dry-run --forward < "$patchfile" >/dev/null 2>&1; then
    # Yocto externalsrc normally skips do_patch: prepare this local source explicitly.
    patch -d "$kernel" -p1 --forward < "$patchfile"
elif ! patch -d "$kernel" -p1 --dry-run --reverse < "$patchfile" >/dev/null 2>&1; then
    echo 'Kernel patch is incompatible' >&2
    exit 1
fi
conf="$target/project-spec/meta-user/conf/petalinuxbsp.conf"
if ! grep -q '# Local WSL build limits' "$conf"; then
    printf '\n# Local WSL build limits (host has 8 GB RAM)\nBB_NUMBER_THREADS = "2"\nPARALLEL_MAKE = "-j2"\n' >> "$conf"
fi
printf '%s\n' 'ADI source: https://github.com/analogdevicesinc/linux' 'Tag: adi-xilinx-2020.1' 'Commit: 4d2388646b4c24b128336077ec55c8068418688a' 'Original author kernel revision is not recorded in this project.' > "$kernel/SOURCE-PROVENANCE.txt"
echo "Project prepared: $target"
head -n 5 "$kernel/Makefile"
